stages:
  - codesigner-dotnet-dll

variables:
  PROJECT_NAME: "HelloWorld"
  PROJECT_VERSION: "0.0.1"
  DOTNET_VERSION: "3.1"

cache:
  paths:
    - ${CI_BUILDS_DIR}/artifacts
    - ${CI_BUILDS_DIR}/packages

prepare:
  stage: codesigner-dotnet-dll
  image: mcr.microsoft.com/dotnet/sdk:3.1-bullseye
  script:
    - mkdir ${CI_BUILDS_DIR}/artifacts
    - mkdir ${CI_BUILDS_DIR}/packages

build:
  stage: codesigner-dotnet-dll
  image: mcr.microsoft.com/dotnet/sdk:3.1-bullseye
  script:
    - dotnet build dotnet/${PROJECT_NAME}.csproj -c Release
    - cp dotnet/bin/Release/netcoreapp${DOTNET_VERSION}/${PROJECT_NAME}-${PROJECT_VERSION}.dll ${CI_BUILDS_DIR}/packages/HelloWorld.dll
  artifacts:
    paths:
      - ${CI_BUILDS_DIR}/packages/HelloWorld.dll
    expire_in: 10 minutes
  dependencies:
    - prepare