language: csharp
mono: none
dotnet: 3.1.419

jobs:
  include:
    - stage: Create Artifacts Directory
      script: 
        # Created directories for artifacts
        - mkdir -p ${CI_PROJECT_DIR}/artifacts
        - mkdir -p ${CI_PROJECT_DIR}/packages

    - stage: Compile Dotnet Library with Dotnet Core
      script:
        # Build dotnet project with Release configuration
        - dotnet build dotnet/${PROJECT_NAME}.csproj -c Release
        # Copy built artifacts to artifacts directory
        - cp dotnet/bin/Release/netcoreapp${DOTNET_VERSION}/${PROJECT_NAME}-${PROJECT_VERSION}.dll ${CI_PROJECT_DIR}/packages/${PROJECT_NAME}.dll