dist: xenial

language: csharp
mono: none
dotnet: 3.1.419

services:
  - docker

env:
  global:
    - PROJECT_NAME="HelloWorld"
    - PROJECT_VERSION="0.0.1"
    - DOTNET_VERSION="3.1"

jobs:
  include:
    - stage: Create Artifacts Directory
      script: 
        # Created directories for artifacts
        - mkdir -p ${TRAVIS_BUILD_DIR}/artifacts
        - mkdir -p ${TRAVIS_BUILD_DIR}/packages

    - stage: Compile Dotnet Library with Dotnet Core
      script:
        # Build dotnet project with Release configuration
        - dotnet build dotnet/${PROJECT_NAME}.csproj -c Release

      after_success:
        # Copy built artifacts to artifacts directory
        - cp dotnet/bin/Release/netcoreapp${DOTNET_VERSION}/${PROJECT_NAME}-${PROJECT_VERSION}.dll ${TRAVIS_BUILD_DIR}/packages/${PROJECT_NAME}.dll
